platform :ios, '17.2'

target 'UMICapture' do
  use_frameworks!
  pod 'Socket.IO-Client-Swift', '~> 16.1.0'

  target 'UMICaptureTests' do
    inherit! :search_paths
  end

  target 'UMICaptureUITests' do
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |configuration|
        configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.2'
      end
    end
  end
end

